ls:
  dir: kebab-case
  .js: kebab-case
  .ts: kebab-case
  .png: kebab-case
  .jpg: kebab-case
  .jpeg: kebab-case
  .svg: kebab-case
  app:
    .tsx: kebab-case
  components:
    .tsx: PascalCase
  constants:
    .ts: PascalCase
  hooks:
    .ts: camelCase

ignore:
  - node_modules
  - .vscode
  - app/**/_layout.tsx
  - app/**/+not-found.tsx
  - assets/images/**/[!@]*@2x.*
  - assets/images/**/[!@]*@3x.*
